name: hellotokyo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37953
title: Hello Tokyo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090a'
    - '#ab8463'
    - '#b4a5a0'
    - '#54735a'
    - '#fbfcff'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
