name: hellotokyo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37953
title: Hello Tokyo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19043f'
    - '#fdfdfd'
    - '#ff00a8'
    - '#a6629f'
    - '#ec95c8'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
