name: hellotokyo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.33899
title: Hello Tokyo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2c31'
    - '#505052'
    - '#d0c7c8'
    - '#ece2e0'
    - '#999596'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
