name: hellotokyo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.33899
title: Hello Tokyo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#bcbebd'
    - '#858688'
    - '#494a4c'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
